### ISSUE TITLE
DNTCommon.Web.Core.ProtectionProviderService

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/DNTCommon.Web.Core#12]
<div dir="rtl">
من وقتی یکبار پروژه رو اجرا میکنم کلید جدیدی ساخته میشه و هیچ مشکلی ندارم

اما وقتی بانک اطلاعاتی رو پاک میکنم کلید جدید ساخته میشه و کلید قبلی هنوز توی کوکی ها هست و زمانی که میخوام کوکی رو بخونم خطا صادر میشه 

که توی لینک زیر قبلا خطا رو گزارش دادم 

https://github.com/VahidN/DNTCommon.Web.Core/issues/9

آیا راهی وجود داره در صورت پاک کردن دیتابیس و  ساخت مجدد آن این خطا دریافت نشه؟ 

یا راهی وجود داره کوکی ها رو پاک کرد؟

**Comment by RezaAVS** [comment]
<div dir="rtl">
من هم این مشکل رو دارم جناب نصیری آیا راه حلی وجود داره؟

**Comment by VahidN** [comment]
<div dir="rtl">

اين خطا كاملا طبيعي هست و اساسا مشكلي نيست كه بخواهد مطرح شود يا پاسخي داشته باشد. تغيير كليد يعني عدم امكان رمزگشايي.
براي پاك كردن كوكي‌ها از نكات [اين مطلب](https://www.dotnettips.info/post/2520/%da%a9%d8%a7%d8%b1-%d8%a8%d8%a7-%da%a9%d9%88%da%a9%db%8c%e2%80%8c%d9%87%d8%a7-%d8%af%d8%b1-asp-net-core) استفاده كنيد

**Comment by sunn789** [comment]
سلام من اصلا دوباره امشب یه پروژه جدید برای انجمن شروع کردم اما باز هم همون
خطا رو میده
میشه لطفا یه بار IIS  رو ریست کنید فقط IIS  مربوط به همین دامنه را

**Comment by VahidN** [comment]
<div dir="rtl">

IIS را ريست كرديد كار نكرده؟ همينطور هست. توضيحات بيشتر [در اينجا](https://www.dotnettips.info/post/2717/%d8%ba%db%8c%d8%b1%d9%85%d8%b9%d8%aa%d8%a8%d8%b1-%d8%b4%d8%af%d9%86-%da%a9%d9%88%da%a9%db%8c%e2%80%8c%d9%87%d8%a7%db%8c-%d8%a8%d8%b1%d9%86%d8%a7%d9%85%d9%87%e2%80%8c%d9%87%d8%a7%db%8c-asp-net-core-%d9%87%d8%a7%d8%b3%d8%aa-%d8%b4%d8%af%d9%87%e2%80%8c%db%8c-%d8%af%d8%b1-iis-%d9%be%d8%b3-%d8%a7%d8%b2-%d8%b1%db%8c%e2%80%8c%d8%a7%d8%b3%d8%aa%d8%a7%d8%b1%d8%aa-%d8%a2%d9%86)
