### ISSUE TITLE
DisplayNameAttribute?

### ISSUE THREAD

**Issue by RezaAVS** [VahidN/DNTCommon.Web.Core#13]
<div dir="rtl">

من برای ساختار چند زبانه DisplayNameAttribute رو override کردم و باتوجه به ساختار چندزبانه ازش استفاده میکنم

` public class DisplayNameLocalizationAttribute : DisplayNameAttribute`

اما زمانی که میخوام نام کنترلر ها رو بدست بیارم نام کنترلرها خالی می باشد
از این تابع استفاده میکنم
GetAllSecuredControllerActionsWithPolicy

**Comment by VahidN** [comment]
<div dir="rtl">

من هيچ علاقه‌اي به پشتيباني راه حل‌هاي سفارشي و شخصي كه حتي مشخص نيست جزئيات آن چيست، ندارم
