### ISSUE TITLE
GetAllSecuredControllerActionsWithPolicy کجاست؟

### ISSUE THREAD

**Issue by mahdisky** [VahidN/DNTCommon.Web.Core#2]
این تابع کجاست؟
GetAllSecuredControllerActionsWithPolicy
تعریف شده فقط پیاده سازیش رو پیدا نکردم؟

**Comment by VahidN** [comment]
https://github.com/VahidN/DNTCommon.Web.Core/search?q=GetAllSecuredControllerActionsWithPolicy&unscoped_q=GetAllSecuredControllerActionsWithPolicy
