### ISSUE TITLE
مقادیر مناسب DurationMin و AllowedRequests در UseAntiDos

### ISSUE THREAD

**Issue by rezaeiy** [VahidN/DNTCommon.Web.Core#3]
<div dir="rtl">

با سلام

مقادیر مناسب برای
DurationMin و AllowedRequests 
چه اعدادی هستن
زمانی که
AllowedRequests
  رو مثلا به 100 برای یک دقیقه تنظیم میکنم پس از بازکردن تعداد صفحات محدودی پیغام محدودیت دیسترسی رو نشون میده

**Comment by VahidN** [comment]
<div dir="rtl">
يعني در هر صفحه‌ي شما تعداد زيادي درخواست (درخواست به تصاوير، فايل‌هاي الحاق شده، ...) به سرور ارسال مي‌شوند.
با سعي و خطا عدد مناسبي را پيدا كنيد
