### ISSUE TITLE
AntiDosMiddleware blocks the requests out of the defined config

### ISSUE THREAD

**Issue by hamed-shirbandi** [VahidN/DNTCommon.Web.Core#4]
I use AntiDosMiddleware in my app and it seems to not work correctly.
Some times when i try to call an api from my app, i get 409 error, but that request is not out of the AllowedRequests that defined in appsettings.json !

I set AllowedRequests to 50 requests per 1 minute and some times my request blocked at 1-10 !
```
.NET Core 2.1
Windows Server 2012 R2
Visual Studio 2017 5.7.6
```

## AntiDosConfig in  appsettings.json:

```
.
.
.
    "BannedIPAddressRanges": [
      // Some samples. Remove them!
      // "192.168.0.0/255.255.255.0", // From "192.168.0.0" to "192.168.0.255"
      // "192.168.0.10 - 192.168.10.20" // From "192.168.0.10" to "192.168.10.20"
      // More samples: https://github.com/jsakamoto/ipaddressrange
    ],
    "DurationMin": 1,
    "AllowedRequests": 50,
    "ErrorMessage": "<html><head><title>Error !</title><meta http-equiv='Content-Type' content='text/html; charset=utf-8' /></head><body><div style='border-color: gray; border-width: 1pt; border-style:solid'><div align='center' style='font-family: Tahoma; font-size: 9pt; direction: rtl; background:#B6B66B'><br /><span style='color:white'>Please come back later!</span><br /><br /></div></div></body></html>",
    "IgnoreLocalHost": true
.
.
.

```

**Comment by VahidN** [comment]
It counts the number of requests to your images, scripts, style sheets too, not just the number of requests to your action methods. If your page has a lot of round trips to the server to access linked resources, you should count them too.

**Comment by hamed-shirbandi** [comment]
thanks to answer.
i have only one simple rest api that return an string. i check your solution and it has only one request to server.

i dont use  services.AddDNTCommonWeb() in startup and i use following lines Instead of it :

services.Configure<AntiDosConfig>(options => configuration.GetSection("AntiDosConfig").Bind(options));
services.AddAntiDosFirewall();

Is that enough? or must add another services too?

**Comment by VahidN** [comment]
Try `v1.3.1`. I added `NullIPv6 = "::1"` check.

**Comment by hamed-shirbandi** [comment]
that's worked. 
thanks to support.
