### ISSUE TITLE
AntiDosMiddleware does not work as expected

### ISSUE THREAD

**Issue by hamed-shirbandi** [VahidN/DNTCommon.Web.Core#5]
I use this AntiDosMiddleware in my app and it seems to not work fine yet.
this middleware ban request out of allowed requests count defined in appsettings.json

I added a db log and this is the result:

![untitled](https://user-images.githubusercontent.com/19574409/45770522-d9612880-bc57-11e8-9050-6946b8adc595.png)

by calling same url Continuously, my IP banned, once in 6th request and once in 37th request  but AllowedRequests is 500 !

**Comment by VahidN** [comment]
If you want to log all of your app's request, you should set the log level to "Debug".

**Comment by hamed-shirbandi** [comment]
ok, i added this db logger into your middleware but the question is why it banned my ip in 6th request?

are you sure about [this condition](https://github.com/VahidN/DNTCommon.Web.Core/blob/156cf5fc2aacd3eb0997bf3717bf752c94abfff8/src/DNTCommon.Web.Core/Security/Firewall/AntiDosFirewall.cs#L379) for verifying dos attack? I think " || clientThrottleInfo.ExpiresAt <= DateTimeOffset.UtcNow " cause the bug.

**Comment by VahidN** [comment]
fixed via #https://github.com/VahidN/DNTCommon.Web.Core/commit/0e44524de6bd4258f8ac2afd7294182ba24f5b00
