### ISSUE TITLE
When PersianDateModelBinder added globaly, it doesn't work

### ISSUE THREAD

**Issue by MohsenM01** [VahidN/DNTCommon.Web.Core#55]
# Summary of the issue

PersianDateModelBinder uses globally not work without BinderAttribute [ModelBinder(BinderType = typeof(PersianDateModelBinder))]
Also totally it doesn't bind value.
## Environment

```
DNTCommon.Web.Core version: 2.9.2
.NET Core SDK version: 5
IDE: vs 16.8.2

**Comment by VahidN** [comment]
Yes.  PersianDateModelBinder doesn't work in .NET 5x anymore! Don't use it!
