### ISSUE TITLE
Avoid sending multiple requests

### ISSUE THREAD

**Issue by OmidRafiee** [VahidN/DNTCommon.Web.Core#57]
Avoid sending multiple forms in .NET MVC
Is there such a feature in this package?

**Comment by VahidN** [comment]
You can use[ the PRG pattern](https://www.dntips.ir/post/1336/%d8%a7%d9%84%da%af%d9%88%db%8c-prg-%d8%af%d8%b1-asp-net-mvc) in for this purpose.

**Comment by OmidRafiee** [comment]
Thanks, I found this [solution ](https://gist.github.com/jyarbro/facb175caed8eb9e2239faf750e37230) and added it.
Can I send a pull request?

**Comment by VahidN** [comment]
I don't suggest using these solutions. Just use the standard PRG pattern which is supported by all of the browsers and works well with pure MVC and also razor pages.
You can have a razor view with Ajax support and in this case the token will not change during the life time of the page (there is no post-back here). Using the PRG pattern and [disabling the submit button on post](https://www.dntips.ir/post/1077/%d8%a7%d8%b3%d8%aa%d9%81%d8%a7%d8%af%d9%87-%d8%a7%d8%b2-%d8%af%da%a9%d9%85%d9%87%e2%80%8c%d9%87%d8%a7%db%8c-css-%d8%aa%d9%88%d8%a6%db%8c%d8%aa%d8%b1-%d8%af%d8%b1-asp-net-mvc-%d9%82%d8%b3%d9%85%d8%aa-%d8%af%d9%88%d9%85) are the best solutions and works everywhere.
