### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task DNTCommon.Web.Core.IWebMailService.SendEmailAsync'

### ISSUE THREAD

**Issue by EhsanBahari** [VahidN/DNTCommon.Web.Core#63]
# Summary of the issue
can u help me? i tried everything about it.
method is ther i can find and useit. but in runtime i get this error

## Environment

        public Task SendEmailAsync(string email, string subject, string message)
        {
            return _webMailService.SendEmailAsync(
                _smtpConfig.Value,
                new[] { new MailAddress { ToName = "", ToAddress = email }, },
                subject,
                message
            );
        }

```
DNTCommon.Web.Core version:  latest
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
Download it again, recompile it, and then republish it.
