### ISSUE TITLE
replace deprecated nuget Microsoft.AspNetCore.App with alternative

### ISSUE THREAD

**Issue by amirhosseini01** [VahidN/DNTCommon.Web.Core#67]
the package [Microsoft.AspNetCore.App](https://www.nuget.org/packages/Microsoft.AspNetCore.App) that referenced at /src/DNTCommon.Web.Core/DNTCommon.Web.Core.csproj has been deprecated.
there is some alternative to replace?

note: i try [_ ](https://stackoverflow.com/questions/76996557/microsoft-aspnetcore-mvc-core-marked-as-deprecated-and-causing-publishing-errors) and [_](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#use-the-aspnet-core-shared-framework), its work but i cant test its really work after installing DNTCommon.Web.Core?!

**Comment by VahidN** [comment]
There is no problem with it. It's not being fetched from the nuget! You are not going to download that package. It's a  `FrameworkReference`.
