### ISSUE TITLE
باگ در تزریق Xss

### ISSUE THREAD

**Issue by KAJOOSH** [VahidN/DNTCommon.Web.Core#68]
سلام
خروجی کد های زیر رو مشاهده کنید.

```
var a = "<h1><a+href=#>HTML+Injection</a></h1>";
var b ="<h1><a href=#>HTML Injection</a></h1>";

var resultA  =_antiXssService.GetSanitizedHtml(a); // output: <h1></h1>
var resultB = _antiXssService.GetSanitizedHtml(b); // output: <h1><a href=#>HTML Injection</a></h1>
```
در تست امنیتی که از سیستم ما شد توانستند با این روش کد خود را تزریق کنند و سیستم رندر کرد.
* آخرین نگارش تست شد.

**Comment by VahidN** [comment]
لطفا آزمايشي را [شبيه به اين موارد](https://github.com/VahidN/DNTCommon.Web.Core/blob/master/src/DNTCommon.Web.Core.Tests/AntiXssServiceTests.cs) ارائه دهيد تا قابل بررسي باشد.
