### ISSUE TITLE
Suggestion: Add some features to IWebMailService

### ISSUE THREAD

**Issue by KiarashS** [VahidN/DNTCommon.Web.Core#7]
Dear,

First of all, thanks for DNTCommon.Web.Core!
Please add `CC`, `BCC` and `Reply-To` to `IWebMailService` service.

**Comment by VahidN** [comment]
Added via #https://github.com/VahidN/DNTCommon.Web.Core/commit/05de57a027a54b3f6cd6b388c1cc0a9de9644729
