### ISSUE TITLE
Sanitized html from tinymCE

### ISSUE THREAD

**Issue by sunn789** [VahidN/DNTCommon.Web.Core#8]
# Summary of the issue
Hello and thanks for sharing your knowledge,
I try to use  AntiXss, Set **appsetings.json** the same as this project add codes in **startup**,
Two line for get configuration data from **appseting** and _one_ for add this [service ](https://github.com/VahidN/DNTCommon.Web.Core),
another hand i have a tinyMCE for get data from my blog when run my project i got the same as paste 
```
<html>
<head>
</head>
<body><p>_antiXssService.GetSanitizedHtml("&lt;A HREF=\"http://www.codeplex.com?url=&frac14;script&frac34;alert(&cent;XSS&cent;)&frac14;/script&frac34;\"&gt;XSS&lt;/A&gt;");</p></body>
</html>
```
test many way: past this code(Html code) on your project but get the same as my project without remove tags
```
<!DOCTYPE html><html><head></head><body><div>&lt;A HREF=\"http://www.codeplex.com?url=&frac14;script&frac34;alert(&cent;XSS&cent;)&frac14;/script&frac34;\&gt;XSS&lt;/A&gt;</div></body></html>
```
 and show return value on Mvc Page as @html.row(...) , => show orginal text with out clean text 
is tahat my mistake to do something?
## Environment

```
The in-use version:MVC core 2.2
Operating system: win 10 x64
IDE: (Visual Studio 2017)

**Comment by VahidN** [comment]
Save your result as an HTML file and then open it with Chrome or Firefox. You won't see an alert or even a clickable link. It's not executable. So it's safe and it doesn't need any cleaning.
