### ISSUE TITLE
DNTCommon.Web.Core.ProtectionProviderService

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/DNTCommon.Web.Core#9]
سلام
توی فایل لاگ این بخش مرتب خطا میده
The key Invalid protected payload. Fall through. was not found in the key ring.
[
  {
    "Key": "e52974eb-b2e5-4ad0-8b8f-d6092646beda",
    "Value": "Invalid protected payload. Fall through."
  },
  {
    "Key": "{OriginalFormat}",
    "Value": "The key {e52974eb-b2e5-4ad0-8b8f-d6092646beda} was not found in the key ring."
  }
]

**Comment by rbsdotnet** [comment]
این خطا هم صادر میشه

Error unprotecting the session cookie.
System.Security.Cryptography.CryptographicException: The key {e52974eb-b2e5-4ad0-8b8f-d6092646beda} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)

**Comment by VahidN** [comment]
To avoid the data protection error, you can run a PowerShell script:
https://raw.githubusercontent.com/aspnet/AspNetCore/master/src/DataProtection/Provision-AutoGenKeys.ps1
Or follow this article in Persian:
https://www.dotnettips.info/post/2717

**Comment by rbsdotnet** [comment]
من از 
IProtectionProviderService
توی سرویسی که برای ذخیره و بازیابی کوکی نوشتم استفاده  کردم دقیقا جایی که میخوام رمزگشایی کنم خطا صادر میشه

 return !_httpContextAccessor.HttpContext.Request.Cookies.TryGetValue(key, out var cookieValue) ? null : _protectionProviderService.Decrypt(cookieValue);

cookieValue  دارای مقدار هم هست

**Comment by RezaAVS** [comment]
اپلیکیشن رو با iisexpress اجرا میکنم
و زمانی که debug میکنم مقدار خروجی decrypt 
null هست

**Comment by RezaAVS** [comment]
وقتی DNTCommon.Web.Core از NUGET میگیرم خطا میده اما وقتی پروژه شما رو از GIT گرفتم و .NETCORE 3.0  رو برداشتم بدون هیچ مشکلی اجرا شد و خطایی صادر نمیشه

**Comment by VahidN** [comment]
<div dir="rtl">

 اين پروژه مالتي تارگت هست و دات نت استاندارد 2 را پشتيباني مي‌كند
netcoreapp3 مربوط به پروژه‌هاي جديد است و تداخلي با كار شما ندارد

**Comment by RezaAVS** [comment]
بله دقیقا همینور هست اما متاسفانه الان وقتی پروژه رو گرفتم و دستی dll رو اضافه کردم هیچ مشکلی نیست
اما وقتی از nuget میگیرم خطا صادر میشه

**Comment by VahidN** [comment]
<div dir="rtl">

سعي كنيد در ويژوال استوديو، امكانات نيوگت آن‌را به روز كنيد كه اين مورد نياز به آپديت خود ويژوال استوديو را دارد
به علاوه تمام اين كارها را بهتر است توسط CLI خود SDK انجام دهيد كه آخرين نگارش NuGet.exe را هم به همراه دارد
dotnet add package DNTCommon.Web.Core
SDK 3 را نصب كنيد. سپس دستور نصب بسته و ري استور را صادر كنيد.

**Comment by RezaAVS** [comment]
<div dir="rtl">
کش Nuget پاک کردم سپس دوبار تماممی nuget ها ری استور شدن سپس درست شد
ممنون از راهنمایی تون.

**Comment by RezaAVS** [comment]
<div dir="rtl">
آیا راهی وجود داره؟ تا هر پروژه کلید مخصوص به خودش رو داشته باشه؟

**Comment by VahidN** [comment]
<div dir="rtl">

هر پروژه از پروژه‌ي ديگر مجزا هست. اين حالت پيش‌فرض آن است. بنابراين اطلاعات رمزگذاري شده‌ي در يكي در ديگري قابل استفاده نيست [مگر اينكه نام برنامه يكي تنظيم شود](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.0#setapplicationname)

**Comment by RezaAVS** [comment]
برای هر پروژه نام مجزا در نظر گرفته شده ولی با این حال باز خطای فوق صادر می شود.
آیا لازم است جدول AppDataProtectionKey هم براساس نام پروژه فیلتر شود؟

**Comment by RezaAVS** [comment]
services.AddSingleton<IXmlRepository, DataProtectionKeyService>();
            services.AddSingleton<IConfigureOptions<KeyManagementOptions>>(serviceProvider =>
            {
                return new ConfigureOptions<KeyManagementOptions>(options =>
                {
                    var scopeFactory = serviceProvider.GetRequiredService<IServiceScopeFactory>();
                    using (var scope = scopeFactory.CreateScope())
                        options.XmlRepository = scope.ServiceProvider.GetService<IXmlRepository>();
                });
            });
            services
                .AddDataProtection()
                .SetApplicationName(siteSettingViewModel.CookieOptionSetting.CookieName)
                .SetDefaultKeyLifetime(siteSettingViewModel.CookieOptionSetting.ExpireTimeSpan)
                .UseCryptographicAlgorithms(new AuthenticatedEncryptorConfiguration
                {
                    EncryptionAlgorithm = EncryptionAlgorithm.AES_256_CBC,
                    ValidationAlgorithm = ValidationAlgorithm.HMACSHA256
                });

**Comment by RezaAVS** [comment]
<div dir="rtl">
جناب نصیری مشکل از انتخاب نام های متفاوت برای هر application بود، وقتی نام ها یکی شد مشکل حل شد
من حتی نام پروژه رو در جدول AppDataProtectionKey  هم گذاشتم درست نشد و در کوئری زیر هم بررسی کردم اما خطا صادر می شد

return _serviceProvider.RunScopedService<ReadOnlyCollection<XElement>, IUnitOfWork>(context =>
            {
                var dataProtectionKeys = context.Set<AppDataProtectionKey>();
                return new ReadOnlyCollection<XElement>(dataProtectionKeys.Select(row => XElement.Parse(row.XmlData)).ToList());
            });
